export const items = [
    {
        id: 1,
        name: "Fleisch",
        description: "Lecker",
        price: 3,
        duration: 30,
        difficulty: "Simple",
        recipePhoto: "",
        ingredients: "2 KG Fliesch",
        preparation: "2 Stunden auf dem Herd",
        category: "Fleisch",
    },
    {
        id: 2,
        name: "Reis",
        description: "Sehr Lecker",
        price: 2,
        duration: 15,
        difficulty: "Simple",
        recipePhoto: "",
        ingredients: "2 KG Reis",
        preparation: "Halbe Stunde auf dem Herd",
        category: "Reis",
    },
    {
        id: 3,
        name: "Nudeln",
        description: "Lecker",
        price: 1,
        duration: 10,
        difficulty: "Simple",
        recipePhoto: "",
        ingredients: "1 KG",
        preparation: "15 Minute auf dem Herd",
        category: "Nudeln",
    },
    {
        id: 4,
        name: "Kuchen",
        description: "Lecker",
        price: 10,
        duration: 60,
        difficulty: "Simple",
        recipePhoto: "",
        ingredients: "2 KG weißes Mehl",
        preparation: "1 Stunde im Backofen",
        category: "Kuchen",
    }
]